const FEATURE_LABELS = ["Climate control", "Stoelen elektrisch verstelbaar", "Elektrische stoelen met geheugenfunctie", "Lendesteun", "Stoelverwarming voor", "Stoelverwarming achter", "Stoelventilatie voor", "Stuurverwarming", "Elektrisch verstelbaar stuur met geheugenfunctie", "Op afstand koelen/verwarmen", "Lane assist", "Adaptive Cruise Control", "One pedal drive", "Park assist", "Achteruitrijcamera", "Automatisch dimmende binnenspiegel", "Automatisch dimmende zijspiegels", "Automatische achterklep", "Geluidsdempend glas"];
const CARS = [
  {
    "id": "tesla-y",
    "brand": "Tesla",
    "model": "Model Y Juniper Long Range",
    "segment": "SUV",
    "price": 950,
    "rangeKm": 622,
    "dcKw": 250,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 854,
    "frunkLiters": 117,
    "confidence": "Hoog",
    "highlights": [
      "Meest complete totaalpakket",
      "Zeer veel ruimte",
      "Sterke laadprestaties"
    ],
    "watchouts": [
      "Hoge maandprijs",
      "Minimalistisch interieur is smaakgevoelig"
    ],
    "features": [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ]
  },
  {
    "id": "vw-id3",
    "brand": "Volkswagen",
    "model": "ID.3 Neo Style",
    "segment": "Hatchback",
    "price": 811,
    "rangeKm": 625,
    "dcKw": 183,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 385,
    "frunkLiters": 0,
    "confidence": "Hoog",
    "highlights": [
      "Beste balans bereik/prijs",
      "Rijke Style-uitrusting",
      "Zeer hoge WLTP-range"
    ],
    "watchouts": [
      "Minder bagageruimte",
      "Geen frunk"
    ],
    "features": [
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0
    ]
  },
  {
    "id": "vw-id4",
    "brand": "Volkswagen",
    "model": "ID.4 Limited Edition 140 kW",
    "segment": "SUV",
    "price": 748,
    "rangeKm": 426,
    "dcKw": 105,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 533,
    "frunkLiters": 0,
    "confidence": "Hoog",
    "highlights": [
      "Beste ruime value-SUV",
      "Veel opties voor het geld",
      "Grote kofferbak"
    ],
    "watchouts": [
      "Lage DC-laadsnelheid",
      "Range minder dan topmodellen"
    ],
    "features": [
      1,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0
    ]
  },
  {
    "id": "mercedes-glb",
    "brand": "Mercedes-Benz",
    "model": "GLB Business Solution AMG",
    "segment": "SUV",
    "price": 1012,
    "rangeKm": 610,
    "dcKw": 320,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 570,
    "frunkLiters": 101,
    "confidence": "Middel",
    "highlights": [
      "Beste laadprestaties",
      "Veel ruimte",
      "Premium uitstraling"
    ],
    "watchouts": [
      "Duurste auto",
      "Stoelcomfort minder compleet dan verwacht"
    ],
    "features": [
      1,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0
    ]
  },
  {
    "id": "volvo-ex40",
    "brand": "Volvo",
    "model": "EX40 Plus Europa",
    "segment": "SUV",
    "price": 967,
    "rangeKm": 575,
    "dcKw": 205,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 410,
    "frunkLiters": 31,
    "confidence": "Hoog",
    "highlights": [
      "Zeer complete uitrusting",
      "Volvo-veiligheid",
      "Goede range"
    ],
    "watchouts": [
      "Relatief duur",
      "Minder ruim dan Model Y/ID.4"
    ],
    "features": [
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0
    ]
  },
  {
    "id": "bmw-ix1",
    "brand": "BMW",
    "model": "iX1 eDrive20 M Sport + Innovation Pack",
    "segment": "SUV",
    "price": 842,
    "rangeKm": 475,
    "dcKw": 130,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 490,
    "frunkLiters": 0,
    "confidence": "Middel/hoog",
    "highlights": [
      "Premium gevoel",
      "Sterke uitrusting",
      "Goede praktische ruimte"
    ],
    "watchouts": [
      "Geen frunk",
      "Prijs/waarde niet uitzonderlijk"
    ],
    "features": [
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0
    ]
  },
  {
    "id": "skoda-epiq",
    "brand": "Skoda",
    "model": "Epiq Business Launch Edition 155 kW",
    "segment": "Compact SUV",
    "price": 668.9,
    "rangeKm": 440,
    "dcKw": 125,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 475,
    "frunkLiters": 25,
    "confidence": "Laag/middel",
    "highlights": [
      "Veelbelovende prijs",
      "Goede ruimte",
      "Interessante range"
    ],
    "watchouts": [
      "Uitvoeringdetails nog onzeker",
      "Niet alle opties hard bevestigd"
    ],
    "features": [
      1,
      0,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0
    ]
  },
  {
    "id": "volvo-ex30",
    "brand": "Volvo",
    "model": "EX30 P3 Core Europa + Climate Pack",
    "segment": "Compact SUV",
    "price": 730,
    "rangeKm": 339,
    "dcKw": 134,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 318,
    "frunkLiters": 7,
    "confidence": "Hoog",
    "highlights": [
      "Compact en betaalbaar",
      "Climate Pack meegenomen",
      "Volvo-veiligheid"
    ],
    "watchouts": [
      "Beperkte range",
      "Kleine bagageruimte",
      "Minder luxe opties"
    ],
    "features": [
      1,
      1,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      0,
      1,
      1,
      1,
      0,
      0,
      0,
      0
    ]
  },
  {
    "id": "vw-id-polo",
    "brand": "Volkswagen",
    "model": "ID. Polo Style 37 kWh 99 kW",
    "segment": "Compact",
    "price": 643,
    "rangeKm": 329,
    "dcKw": 90,
    "acKw": 11,
    "doors": 5,
    "trunkLiters": 435,
    "frunkLiters": 0,
    "confidence": "Middel",
    "highlights": [
      "Laagste leaseprijs",
      "Compact formaat",
      "Style-pakket meegenomen"
    ],
    "watchouts": [
      "Beperkte range",
      "Minder compleet",
      "Lage DC-laadsnelheid"
    ],
    "features": [
      1,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0
    ]
  }
];
